# Example  .gitlab-ci.yml file
stages:
  - mavenbuild
  - maventest
  - mavenDeploy
  - androidbuild
  - androidtest
before_script:
  - export JAVA_HOME="/"

maven-build:
  only:
    refs:
      - main
    changes:
      - Backend/Spring
  stage: mavenbuild
  tags:
    - -springboot_tag
  script:
    - cd Backend/Spring
    - mvn package -B
    
maven-test:
  only:
    refs:
      - main
    changes:
      - Backend/Spring
  stage: maventest
  tags:
    - -springboot_tag
  script:
    - cd Backend/Spring
    - mvn test
  artifacts:
    paths:
      - Backend/Spring/target/*.jar

# Below job builds, deploys, executes jar as service.
autoDeploy:
  only:
    refs:
      - main
    changes:
      - Backend/Spring
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - -springboot_tag
  script:
    - cd Backend/Spring
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo


android-build:
  only:
    refs:
      - main
    changes:
      - Frontend/StudyBuddies
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/StudyBuddies/gradlew
  tags:
   - -android_tag
  script:
    - cd Frontend/StudyBuddies
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  only:
    refs:
      - main
    changes:
      - Frontend/StudyBuddies
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/StudyBuddies/gradlew
  tags:
   - -android_tag
  script:
    - cd Frontend/StudyBuddies
    - ./gradlew test

