package org.springframework.studybuddies.personalEvents;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.springframework.core.style.ToStringCreator;
import org.springframework.studybuddies.group.Groups;
import org.springframework.studybuddies.members.MembersTable;

import io.swagger.annotations.ApiModelProperty;

/**
 * @author Ryan Sand and Brady Heath
 */

@Entity
@Table(name = "personalEvents")
public class personalEvents {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "groupEventid")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "Autogenerated ID", name = "PEid", required = true, value = "2")
	private Integer PEid;

	@Column(name = "time")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "The time the personal event was posted", name = "time", required = true, value = "2:57pm")
	private String time;

	@Column(name = "message")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "The text message that was attached with the personal event", name = "message", required = true, value = "Meeting with team today!")
	private String message;


	@Column(name = "eventMemberId")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "The number associated with the member that posted the personal event", name = "eventMemberId", required = true, value = "1")
	private Integer eventMemberId;

	@ManyToOne
	@JoinColumn(name = "eventMemberId", referencedColumnName = "memberId", nullable = false, insertable = false, updatable = false)
	private MembersTable memberSave;

	public personalEvents() {

	}

	public personalEvents(int PEid, String time, String message, int eventMemberId) {
		this.PEid = PEid;
		this.time = time;
		this.message = message;
		this.eventMemberId = eventMemberId;
	}
	
	
	

	// ID
	public Integer getId() {
		return PEid;
	}

	public void setId(Integer PEid) {
		this.PEid = PEid;
	}

	// Time
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	// Message
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	
	// Member Id
	public Integer geteventMemberId() {
		return this.eventMemberId;
	}

	public void seteventMemberId(int eventMemberId) {
		this.eventMemberId = eventMemberId;
	}
	
	public MembersTable getMembersDetail() {
		return memberSave;
	}

	@Override
	public String toString() {
		return new ToStringCreator(this)

				.append("id", this.getId()).append("time", this.getTime())
				.append("message", this.getMessage()).toString();
	}
}