package org.springframework.studybuddies.announcement;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.springframework.core.style.ToStringCreator;

import io.swagger.annotations.ApiModelProperty;

/**
 * @author Ryan Sand and Brady Heath
 */

@Entity
@Table(name = "announcements")
public class Announcements {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "Autogenerated ID",name="id",required=true,value="2")
	private Integer id;

	@Column(name = "username")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "The name that the user is identified as on the app",name="username",required=true,value="JohnSm1th52")
	private String username;

	@Column(name = "password")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "The password used to authenticate the user",name="password",required=true,value="HkO09Ji8*sL2-pN")
	private String password;

	@Column(name = "email")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "The email linked to a user's account on the app",name="email",required=true,value="jsmith@gmail.com")
	private String email;

	@Column(name = "location")
	@NotFound(action = NotFoundAction.IGNORE)
	@ApiModelProperty(notes = "The location of the user, used to find nearby study groups",name="location",required=true,value="Ames")
	private String location;

	Group ID (Foreign Key)
	Member ID (Foreign Key)
	Time
	Message

	
	public Announcements() {

	}

	public Announcements(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;

	}

	// ID
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	// Username
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	// Password
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	// Email
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	// Location
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Override
	public String toString() {
		return new ToStringCreator(this)

				.append("id", this.getId()).append("username", this.getUsername())
				.append("password", this.getPassword()).append("email", this.getEmail())
				.append("location", this.getLocation()).toString();
	}
}
